---
- name: run Python script
  hosts: all
  tasks:
    - name: run inter.py script
      script:
        executable: python3
        cmd: /var/lib/awx/projects/inter.py
        remote_src: True
      register: cars_raw_output
    - name: print cars_raw_output
      debug:
        var: cars_raw_output
