- name: copy and execute script
  hosts: all
  tasks:

     - name: copy files from source to remote servers
       copy:
        src: /var/lib/awx/projects/inter.py
        dest: /home/vagrant/
        mode: 0777
        
     - name: Execute script for rhel/centos 6 servers
       become: yes
       command: "python3 /home/vagrant/inter.py"
